# Generated by Django 4.1.2 on 2023-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('new_images_number', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('test_loss', models.FloatField(default=-1.0)),
                ('test_accuracy', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.TextField()),
                ('label', models.IntegerField(choices=[(0, 'Lanternfly'), (1, 'Not Lanternfly'), (2, 'Not Labeled')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.TextField()),
                ('label', models.IntegerField(choices=[(0, 'Lanternfly'), (1, 'Not Lanternfly'), (2, 'Not Labeled')], default=2)),
                ('status', models.IntegerField(choices=[(1, 'Not used in app'), (2, 'Was labeled in app')], default=1)),
                ('date_labeled', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
